services:
  - type: web
    name: aluta-market-api
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:#weareALUTA001@db.xtveecfkozofkexhhjxt.supabase.co:5432/postgres
      - key: PORT
        value: 8080
      - key: 2LzVCRlQg94mjLp8pMYPDqGv1BaVN2Cizn3GF/7kt10=
        sync: false
      - key: Qrk+hzGAZ/ENR6Up/VQ6dEwbMjbN8ir0naffcmpdUxc=
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: aluta_market_db
    databaseName: postgres
    user: postgres
    plan: free