services:
  - type: web
    name: aluta-market-api
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aluta_market_db
          property: connectionString
      - key: PORT
        value: 8080
      - key: SECRET_KEY
        sync: false
      - key: REFRESH_SECRET_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: aluta_market_db
    databaseName: postgres
    user: postgres
    plan: free