services:
  - type: web
    name: aluta-market-api
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: DB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: REFRESH_SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false